services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Pixelant\PxaSocialFeed\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'
  Pixelant\PxaSocialFeed\Controller\AdministrationController:
    tags: ['backend.controller']
